#!/bin/bash
# TX-Packages Android NDK Setup Script
# Automatically detects, downloads, or configures the Android NDK

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

# Configuration
NDK_VERSION="${NDK_VERSION:-r27c}"
ANDROID_API="${ANDROID_API:-29}"
TARGET_ARCH="${TARGET_ARCH:-aarch64}"
TARGET_TRIPLE="${TARGET_TRIPLE:-aarch64-linux-android}"
TARGET_ABI="${TARGET_ABI:-arm64-v8a}"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Detect existing NDK
detect_ndk() {
    log_info "Detecting Android NDK..."

    # Check environment variables
    if [ -n "${ANDROID_NDK_HOME:-}" ] && [ -d "$ANDROID_NDK_HOME" ]; then
        echo "$ANDROID_NDK_HOME"
        return 0
    fi

    if [ -n "${ANDROID_NDK:-}" ] && [ -d "$ANDROID_NDK" ]; then
        echo "$ANDROID_NDK"
        return 0
    fi

    # Check common locations
    local locations=(
        "$HOME/Android/Sdk/ndk"
        "$HOME/android-ndk"
        "/usr/local/android-ndk"
        "/opt/android-ndk"
    )

    for loc in "${locations[@]}"; do
        if [ -d "$loc" ]; then
            # Check for version subdirectories
            if [ -d "$loc/toolchains" ]; then
                echo "$loc"
                return 0
            fi

            # Check version subdirectories
            local versions=()
            for d in "$loc"/*/; do
                if [ -d "$d/toolchains" ]; then
                    versions+=("$d")
                fi
            done

            if [ ${#versions[@]} -gt 0 ]; then
                # Return newest version
                IFS=$'\n' sorted=($(sort -r <<<"${versions[*]}"))
                unset IFS
                echo "${sorted[0]}"
                return 0
            fi
        fi
    done

    return 1
}

# Download NDK
download_ndk() {
    local dest="$1"
    local ndk_zip="android-ndk-${NDK_VERSION}-linux.zip"
    local ndk_url="https://dl.google.com/android/repository/${ndk_zip}"

    log_info "Downloading Android NDK ${NDK_VERSION}..."
    log_info "URL: ${ndk_url}"
    log_info "Destination: ${dest}"

    mkdir -p "$dest"
    cd "$dest"

    if command -v curl &> /dev/null; then
        curl -L --progress-bar "$ndk_url" -o "$ndk_zip"
    elif command -v wget &> /dev/null; then
        wget --show-progress -O "$ndk_zip" "$ndk_url"
    else
        log_error "Neither curl nor wget found. Please install one."
        return 1
    fi

    log_info "Extracting NDK..."
    unzip -q "$ndk_zip"
    mv "android-ndk-${NDK_VERSION}"/* .
    rm -rf "android-ndk-${NDK_VERSION}" "$ndk_zip"

    log_info "NDK downloaded successfully"
}

# Verify NDK installation
verify_ndk() {
    local ndk_path="$1"
    local errors=0

    log_info "Verifying NDK installation at ${ndk_path}..."

    # Check essential tools
    local tools=(
        "toolchains/llvm/prebuilt/linux-x86_64/bin/${TARGET_TRIPLE}${ANDROID_API}-clang"
        "toolchains/llvm/prebuilt/linux-x86_64/bin/ld.lld"
        "toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar"
        "toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-strip"
    )

    for tool in "${tools[@]}"; do
        local tool_path="${ndk_path}/${tool}"
        if [ -f "$tool_path" ]; then
            log_info "  Found: ${tool}"
        else
            log_warn "  Missing: ${tool}"
            ((errors++)) || true
        fi
    done

    # Check sysroot
    if [ -d "${ndk_path}/toolchains/llvm/prebuilt/linux-x86_64/sysroot" ]; then
        log_info "  Sysroot found"
    else
        log_warn "  Sysroot not found"
        ((errors++)) || true
    fi

    if [ "$errors" -eq 0 ]; then
        log_info "NDK verification passed"
        return 0
    else
        log_warn "NDK verification had ${errors} warnings"
        return 1
    fi
}

# Generate environment file
generate_env() {
    local ndk_path="$1"
    local env_file="${REPO_ROOT}/.env"

    log_info "Generating environment file: ${env_file}"

    cat > "$env_file" << EOF
# TX-Packages Environment
# Generated by setup-ndk.sh

# Android NDK
export ANDROID_NDK_HOME=${ndk_path}
export ANDROID_NDK=${ndk_path}
export ANDROID_API=${ANDROID_API}
export ANDROID_ABI=${TARGET_ABI}

# Toolchain
export PATH="${ndk_path}/toolchains/llvm/prebuilt/linux-x86_64/bin:\${PATH}"
export CC="${ndk_path}/toolchains/llvm/prebuilt/linux-x86_64/bin/${TARGET_TRIPLE}${ANDROID_API}-clang"
export CXX="${ndk_path}/toolchains/llvm/prebuilt/linux-x86_64/bin/${TARGET_TRIPLE}${ANDROID_API}-clang++"
export AR="${ndk_path}/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar"
export RANLIB="${ndk_path}/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ranlib"
export STRIP="${ndk_path}/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-strip"
export LD="${ndk_path}/toolchains/llvm/prebuilt/linux-x86_64/bin/ld.lld"

# Target
export TARGET_ARCH=${TARGET_ARCH}
export TARGET_TRIPLE=${TARGET_TRIPLE}
export TARGET_ABI=${TARGET_ABI}

# Flags
export CFLAGS="--target=${TARGET_TRIPLE}${ANDROID_API} --sysroot=${ndk_path}/toolchains/llvm/prebuilt/linux-x86_64/sysroot -fPIC -O2"
export CXXFLAGS="\${CFLAGS} -stdlib=libc++"
export LDFLAGS="--target=${TARGET_TRIPLE}${ANDROID_API} --sysroot=${ndk_path}/toolchains/llvm/prebuilt/linux-x86_64/sysroot -fuse-ld=lld -stdlib=libc++"

# TX Packages
export TX_PACKAGES_ROOT=${REPO_ROOT}
EOF

    log_info "Environment file created. Source it with:"
    log_info "  source ${env_file}"
}

# Main
main() {
    log_info "TX-Packages NDK Setup"
    log_info "===================="
    log_info "NDK Version: ${NDK_VERSION}"
    log_info "Android API: ${ANDROID_API}"
    log_info "Target: ${TARGET_TRIPLE}"

    # Detect or download NDK
    local ndk_path
    if ndk_path=$(detect_ndk); then
        log_info "Found existing NDK: ${ndk_path}"
    else
        log_warn "No existing NDK found"

        # Ask to download
        if [ "${AUTO_DOWNLOAD:-}" = "1" ]; then
            ndk_path="${REPO_ROOT}/toolchains/android-ndk-${NDK_VERSION}"
            download_ndk "$ndk_path"
        else
            log_info "Set AUTO_DOWNLOAD=1 to download automatically"
            log_error "NDK not found. Please install the Android NDK."
            exit 1
        fi
    fi

    # Verify
    verify_ndk "$ndk_path"

    # Generate environment
    generate_env "$ndk_path"

    log_info "Setup complete!"
    log_info "Run 'source .env' to load environment variables"
}

main "$@"
